spring:
  datasource:    # datasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${ENV_MYSQL_HOST:127.0.0.1}:${ENV_MYSQL_PORT:3306}/${ENV_MYSQL_DB_NAME:ddl_transaction_example}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&&serverTimezone=UTC
    username: ${ENV_MYSQL_USER:root}
    password: ${ENV_MYSQL_PWD:root}
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  main:
    allow-bean-definition-overriding: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-ddl-transaction-example.yaml
    enabled: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 10240MB

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/*.xml,classpath:com/jjs/ddl/transaction/dao/xml/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yunli.smartcity.dynamicform.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-field: isDeleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

